apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: frbht3l09-go 
  janus-idp.io/tekton: frbht3l09-go
  backstage.io/kubernetes-id: frbht3l09-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: frbht3l09-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml