apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: frbht3l09-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9026a86c95929b14ffdb4858cbb9b1677b3f47e2@sha256:a3bace5f6f262104a8f73106c45d1b02beab7b126c39a8f3ab22ca16dff276ae
          name: container-image
